### PR TITLE
feat: added timestamp field validation in e2e and fixed missing timestamp bug in java src

### LINKED ISSUE #381: Make test log consistent
### TL;DR

See context 
https://github.com/abcxyz/lumberjack/pull/368#discussion_r1103233766

### Detailed design

_No response_

### Alternatives considered

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by capri-xiyue**
part of #381 
1. added timestamp in java logging shell
2. not override `resource` field when generating logentry in java
3. added `timestamp` field validation

### CODE REVIEW

File: clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java [hunk 1]
```diff
@@ -84,8 +85,9 @@ public AuditLogRequest process(AuditLogRequest auditLogRequest) throws LogProces
                   Instant.ofEpochSecond(
                       auditLogRequest.getTimestamp().getSeconds(),
                       auditLogRequest.getTimestamp().getNanos()))
-              .setResource(MonitoredResource.newBuilder(MONITORED_RESOURCE_TYPE).build())
+              // .setResource(MonitoredResource.newBuilder(MONITORED_RESOURCE_TYPE).build())
```
Comment (sethvargo) [inline clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:88]: Is this intended?

Comment (capri-xiyue) [reply clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:88]: I have not finished the change. I'm on the debugging process. No need to take a look at it now. But this change is intended. I found that our go code https://github.com/abcxyz/lumberjack/blob/554bab0378f22d2935cb8630e4c7e89f3fc8a908/clients/go/pkg/cloudlogging/processor.go#L128 doesn't override the `resource` field. Maybe we make both java and go consistent in setting the `resource` field. And based on our doc, this field can be auto generated by cloud logging. I don't see any value of overridden it by ourselves. Did I miss any context?

Comment (capri-xiyue) [reply clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:88]: In addition, this part causes null fields in json maps which triggers incomplete unmarshal due to limitation in protojson. With the limitation of https://github.com/golang/protobuf/issues/1313, we won't be able to verify the timestamp is set in our e2e test and our test is also fragile. Therefore, I try to make the test logs without any null value in json maps or json arrays.

File: clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java [hunk 2]
```diff
@@ -84,7 +83,6 @@ public AuditLogRequest process(AuditLogRequest auditLogRequest) throws LogProces
                   Instant.ofEpochSecond(
                       auditLogRequest.getTimestamp().getSeconds(),
                       auditLogRequest.getTimestamp().getNanos()))
-              .setResource(MonitoredResource.newBuilder(MONITORED_RESOURCE_TYPE).build())
```
Comment (capri-xiyue) [inline clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:87]: This change is intended. I found that our go code https://github.com/abcxyz/lumberjack/blob/554bab0378f22d2935cb8630e4c7e89f3fc8a908/clients/go/pkg/cloudlogging/processor.go#L128 doesn't override the `resource` field. I think we need to make both java and go consistent in setting the `resource` field. And based on our doc, this field can be auto generated by cloud logging. I don't see any value of overridden it by ourselves.

Comment (capri-xiyue) [reply clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:87]: In addition, this part causes null fields in json maps which triggers incomplete unmarshal due to limitation in protojson. With the limitation of https://github.com/golang/protobuf/issues/1313, we won't be able to verify the timestamp is set in our e2e test and our test is also fragile(fields whose order is after `resource` field can't be unmarshalled). Therefore, I try to make the test logs without any null value in json maps or json arrays. I still prefer not to changing the src code just to make test log consistent. But in this case, we have inconsistency in java and go src code when setting `resource` field, I think it makes sense to let java follow the go business logic which let cloud logging to auto generate the `resource` field.

File: integration/testrunner/db.go [hunk 3]
```diff
@@ -66,13 +66,10 @@ func queryAuditLogs(ctx context.Context, tb testing.TB, query *bigquery.Query) [
 		if !ok {
 			tb.Fatalf("error converting query (%T) to string: %v", value[0], err)
 		}
-
+		tb.Logf("bq row is %s", value)
```
Comment (sqin2019) [inline integration/testrunner/db.go:69]: Is this intended or a residual of your debug?

File: clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java [hunk 4]
```diff
@@ -23,7 +23,6 @@
 import com.fasterxml.jackson.core.JsonProcessingException;
 import com.fasterxml.jackson.core.type.TypeReference;
 import com.fasterxml.jackson.databind.ObjectMapper;
-import com.google.cloud.MonitoredResource;
 import com.google.cloud.logging.LogEntry;
 import com.google.cloud.logging.Logging;
 import com.google.cloud.logging.LoggingException;
```
Comment (sqin2019) [inline clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:28]: nit: may need to remove line `private static final String MONITORED_RESOURCE_TYPE = "global";` if no other usage of it.

File: integration/testrunner/db.go (hunk 3 above)
Comment (capri-xiyue) [reply integration/testrunner/db.go:69]: Intended. During this debug, I found it is important to see what the bq row is becauase it could be different from the unmarshalled logentry. And this log will only appear when test fails.

**Review by sqin2019 — APPROVED** [review]

File: clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java (hunk 2 above)
Comment (yolocs) [reply clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java:87]: No. I thought cloud logging would fill this part. It's not critical to the audit logging.

File: clients/java-logger/shell/src/main/java/com/abcxyz/lumberjack/loggingshell/LoggingController.java [hunk 5]
```diff
@@ -41,14 +44,19 @@ public class LoggingController {
...
   @ResponseStatus(value = HttpStatus.OK)
   void loggingShell(
       @RequestParam(value = TRACE_ID_PARAMETER_KEY) String traceId,
       @RequestAttribute(TokenInterceptor.INTERCEPTOR_USER_EMAIL_KEY) String userEmail)
       throws LogProcessingException {
+    Instant now = clock.instant();
     AuditLogRequest record =
         AuditLogRequest.newBuilder()
+            .setTimestamp(
+                Timestamp.newBuilder().setSeconds(now.getEpochSecond()).setNanos(now.getNano()))
```
Comment (yolocs) [inline clients/java-logger/shell/src/main/java/com/abcxyz/lumberjack/loggingshell/LoggingController.java:59]: So cloud logging doesn't fill the timestamp automatically?

**Review by yolocs — APPROVED** [review]

File: clients/java-logger/shell/src/main/java/com/abcxyz/lumberjack/loggingshell/LoggingController.java (hunk 5 above)
Comment (capri-xiyue) [reply clients/java-logger/shell/src/main/java/com/abcxyz/lumberjack/loggingshell/LoggingController.java:59]: cloud logging set timestamp when no timestamp is provided
But in our code, we set the timestamp as null when no timestamp field is set in the auditlog request
Therefore, cloud logging won't set the timestamp for us
See code here
https://github.com/abcxyz/lumberjack/blob/554bab0378f22d2935cb8630e4c7e89f3fc8a908/clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/CloudLoggingProcessor.java#L85A

Comment (capri-xiyue) [reply clients/java-logger/shell/src/main/java/com/abcxyz/lumberjack/loggingshell/LoggingController.java:59]: And see docs here `If this field is omitted in a new log entry, then Logging assigns it the current time.`
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry. We didn't omit that field in our generated log entry
